/*!
    \file request_server.h
    \brief Nanomsg request server definition
    \author Ivan Shynkarenka
    \date 02.02.2017
    \copyright MIT License
*/

#ifndef CPPSERVER_NANOMSG_REQUEST_SERVER_H
#define CPPSERVER_NANOMSG_REQUEST_SERVER_H

#include "server.h"

namespace CppServer {
namespace Nanomsg {

//! Nanomsg request server
/*!
    Nanomsg request server is used to receive requests from Nanomsg clients
    and reply with corresponding responses.

    This protocol is used to distribute the workload among multiple stateless
    workers.

    Please note that request/reply applications should be stateless.

    It's important to include all the information necessary to process the
    request in the request itself, including information about the sender or
    the originator of the request if this is necessary to respond to the request.

    Sender information cannot be retrieved from the underlying socket connection
    since, firstly, transports like IPC may not have a firm notion of a message
    origin. Secondly, transports that have some notion may not have a reliable one
    - a TCP disconnect may mean a new sender, or it may mean a temporary loss in
    network connectivity.

    For this reason, sender information must be included by the application if
    required. Allocating 6 randomly-generated bytes in the message for the lifetime
    of the connection is sufficient for most purposes. For longer-lived
    applications, an UUID is more suitable.

    Thread-safe.
*/
class RequestServer : public Server
{
public:
    //! Initialize server with a given endpoint address
    /*!
        \param address - Endpoint address
        \param threading - Run the server in a separate thread (default is true)
    */
    explicit RequestServer(const std::string& address, bool threading = true)
        : Server(CppServer::Nanomsg::Domain::Std, CppServer::Nanomsg::Protocol::Reply, address, threading)
    {}
    RequestServer(const RequestServer&) = delete;
    RequestServer(RequestServer&&) noexcept = default;
    virtual ~RequestServer() = default;

    RequestServer& operator=(const RequestServer&) = delete;
    RequestServer& operator=(RequestServer&&) noexcept = default;
};

/*! \example nanomsg_request_server.cpp Nanomsg request server example */

} // namespace Nanomsg
} // namespace CppServer

#endif // CPPSERVER_NANOMSG_REQUEST_SERVER_H
