name: Linux (clang)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup required packages"
        run: sudo apt-get install -y binutils-dev libc++-dev libssl-dev uuid-dev

      - name: "Setup clang"
        uses: egor-tensin/setup-clang@v1

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Build"
        run: |
          cd build
          ./unix.sh
