name: MacOS

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Setup python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: "Setup cmake"
        run: cmake --version

      - name: "Setup gil"
        run: |
          pip3 install gil
          gil update

      - name: "Setup UDP multicast route"
        run: sudo route -nv add -net 239.0.0.0/8 -interface lo0

      - name: "Build"
        run: |
          cd build
          ./unix.sh
